### ISSUE TITLE
ポイントシステムとしての機能要件洗い出し

### ISSUE THREAD

**Issue by m-chiaki** [TechTeam-org/public-tasks#154]
### 概要
- メニューを除くポイントシステム自体の要件を洗い出す

### 目的
- 機能要件を明確化する

### task
- [x] メイン機能の洗い出し
- [x] それぞれのメイン機能の要件化
- [x] 一次レビュー(3月中)
- [x] 二次レビュー(4/7)

**Comment by m-chiaki** [comment]
## メイン機能
- 「貯める」：会員がコミュニティにとって有益な行動をとった際に、その報奨として「ポイント」を付与できる
- 「使う」：会員が貯めたポイントをリワードと変換できる
- 「管理する」：会員が付与されたポイント、付与予定のポイント、使用したポイントを確認できる

## 詳細
### 貯める
- 何かと連動して(サブスク購入など)自動的にポイントを付与できること・・・これが一番考えないといけないと思っている
- 運営側がポイントを付与できること・・・ポイント付与メニューでこれも必要になると思う。人的管理なる悩みどころ。
- 付与されたポイントは当月中は付与予定ポイントとなり、付与予定ポイントとして表示できる。
- 次月頭に確定ポイントとして付与ポイントとなり、付与ポイントに加算され表示できる。
※貢献度に応じてランクつけたり、キャンペーンでポイント付与のパーセント変えるとか色々考えると出るけど。。。今時点ではやめましょう。
### 使う
- ポイント利用メニューを表示できること
- ポイント表示メニューを選択し、リワードとしてポイントと変換できること
- 変換されたリワードはクーポンとしてマイページに表示できること（こういう仕様で良い？）
- クーポンの利用方法①：サブスク購入時クーポンの利用コードを入力すると割引でき、クーポンが使用済みとなる。
- クーポンの利用方法②：「利用する」を押下すると使用済みにできる
### 管理する
- 溜まっているポイントの累計を確認できること
- 当月利用により、次月付与される予定のポイントを確認できること
- 過去に付与されたポイント、使用したポイントの履歴を確認できること
- 過去にポイントが付与された事由、ポイントを使用した自由が確認できること(何でもらい何で利用したのか)

### バックエンド側の機能
- 運営側で必要な機能。。。考えてなかった。情報不整合とかトラブル時で使えるAPIとか。

**Comment by leo-kaiD** [comment]
@Daiki-Ishii 
レビューお願いしますー！

**Comment by Daiki-Ishii** [comment]
問題ないです🙆‍♀️
ありがとうございます！

**Comment by suguru-toyohara** [comment]
こちら、「渡す」という機能も考えないといけないですね。

**Comment by suguru-toyohara** [comment]
@m-chiaki 
Q&Aなどの「渡す」についても考えていただきたいです。
ポイント付与などは次月頭というのはいいと思います。
他も大丈夫です。

**Comment by m-chiaki** [comment]
@suguru-toyohara 
ご確認ありがとうございます
以下を追記しました。

### 渡す
- 任意のユーザーへ自分のポイントを譲渡できること(一例としてyahoo知恵袋でのベストアンサーへのコイン付与のようなもの)
- ポイント譲渡を実施するかどうかは任意で選択できるようにすること
- 譲渡されたポイントは通常貯めるポイントと同様に当月中は付与予定ポイントとなり、次月頭に確定ポイントとして付与ポイントとなること

**Comment by suguru-toyohara** [comment]
一旦進めちゃいましょう。
