### ISSUE TITLE
ポイントシステムのメニュー洗い出し

### ISSUE THREAD

**Issue by m-chiaki** [TechTeam-org/public-tasks#155]
### 概要
- ポイントのメニューを検討する

### 目的
- 付与条件、利用条件を明確にする

### task
- [x] ポイント付与メニューの検討
- [x] ポイント利用メニューの検討
- [x] 一次レビュー(3月中)
- [x] 二次レビュー(4/7)

**Comment by m-chiaki** [comment]
## ポイント付与メニュー
### 利用
- 購入に対して(開発環境のサブスク等)
- yahoo知恵袋的なの作るのもあり？
### 営業
- 案件情報の提供、仲介
### 開発
- 内部開発の実施
- 受注案件の実施
### 組織拡大
- 勉強会のスピーカー実施
- 交流会への新規参加者動員
- discordへ新規参加者追加
- SNSでのコミュニティ拡散

## ポイント利用メニュー
- 何かの購入に利用できる(開発環境のサブスク等)
- 交流会の参加割引
- 外部サービスとの提携(知り合いのお店の割引に使えるとか。。。)
※利用メニューは後々増やしていくでも良いかなと。機能としてメニュー増えても影響ないのかなと思うため。

**Comment by m-chiaki** [comment]
@Daiki-Ishii 
レビューお願いしますー！

**Comment by Daiki-Ishii** [comment]
問題ないです🙆‍♀️
ありがとうございます🙇‍♀️

**Comment by Daiki-Ishii** [comment]
問題ないです🙆‍♀️
ありがとうございます🙆‍♀️
以前話した内容に齟齬はないので！

**Comment by suguru-toyohara** [comment]
> 組織拡大

これ何を指していますか...？

**Comment by suguru-toyohara** [comment]
> 購入に対して(開発環境のサブスク等)

こちら、具体的ではないものの、こうとしか書けないので、多分これで大丈夫かと！

**Comment by suguru-toyohara** [comment]
あと、ここには書かれてないですが、
トロフィーとしてのポイント活用もアリかなと思います。
獲得総ポイント数とかあると良いかもです。
（貯められると一気に利用された時に困る＋使い道も困るのでそういう使い方は推奨されない）

**Comment by suguru-toyohara** [comment]
@Daiki-Ishii 
組織拡大とトロフィーとしてのポイント制度
あとDiscordの特別なロール付与なども踏まえてポイントシステムのメニューを考えていただけると！

**Comment by Daiki-Ishii** [comment]
確認ありがとうございます🥲
上記踏まえてメニューの考案進めます

**Comment by m-chiaki** [comment]
@Daiki-Ishii 
一応レビューコメントに対しての松元コメントです。
勘案して、最終的なアウトプットお願いします。

>組織拡大
>これ何を指していますか...？
TechTeamの人数規模を大きくすることを指しています。
SNS拡散や交流会等への動員など人数を増やす活動に対して一定のポイントを付与することを検討。
交流会の友達割やSNS拡散割が合ったと思いますが、そう言ったものをポイントとして還元でも良いのかなという意見。
（交流会等の友達割やSNS拡散の割引は現金でやってしまうのもあり。先日話していたSNSの100円割引をポイント化してしまうも良いかなと）

@suguru-toyohara 
すみませぬ。。。トロフィーってどういう制度でしょう？一般的によく使われてます？
何か参考サイトあれば教えてくださいませ。（ @Daiki-Ishii がわかってる感じなら問題ないのでその旨コメントください ）

**Comment by Daiki-Ishii** [comment]
[TechTeam ポイントシステム メニュー一覧.pptx](https://github.com/TechTeam-org/public-tasks/files/15050290/TechTeam.pptx)

**Comment by suguru-toyohara** [comment]
良きです！
