### ISSUE TITLE
通知botでtaskの複数担当者を出現するようにする

### ISSUE THREAD

**Issue by leo-kaiD** [TechTeam-org/public-tasks#201]
### 概要
- 通知botで複数担当者を出現するようにする

### 目的
- 現状取得できた担当者が複数いても1人しか通知されないので通知されるように回収する

### task
- [x] 実装修正
- [x] test

**Comment by leo-kaiD** [comment]
![Image](https://github.com/TechTeam-org/public-tasks/assets/159105331/2706b171-8c81-41fd-8262-9156b2634462)


しっかり2人分の通知は入ってるかなと

**Comment by leo-kaiD** [comment]
![Image](https://github.com/TechTeam-org/public-tasks/assets/159105331/bd462103-6db4-4331-991d-1699b083b379)

4人分でもフォーマット壊れ無くした

**Comment by Daiki-Ishii** [comment]
エビデンス問題ないのでdone
